name: Meta Ad Studio CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run asset integrity check
      run: node scripts/ci-check-assets.cjs

    - name: Run linter
      run: npm run lint

    - name: Run unit tests
      run: npm test -- --run

    - name: Run production build (with sourcemaps)
      env:
        NODE_ENV: production
      run: |
        # Ensure Vite emits source maps for release uploads
        npm run build

    - name: Upload source maps to Sentry (optional)
      if: secrets.SENTRY_AUTH_TOKEN != ''
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      run: |
        echo "Sentry upload step placeholder - configure sentry-cli or vite-plugin-sentry in your pipeline"

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run E2E Tests with High-Fidelity API Server
      run: npm run test:e2e
      env:
        CI: true

    - name: Upload Playwright artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-artifacts
        path: |
          test-results/**
          playwright-report/**
          .playwright/**

    - name: Package release zip
      run: |
        zip -r meta-ad-studio-platform-v1.0.zip . -x node_modules/**\* .git/**\* tests/**\*
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: meta-ad-studio-platform-v1.0.zip
        path: meta-ad-studio-platform-v1.0.zip

  e2e-demo-validation:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install system deps (ffmpeg)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run full local demo orchestration (generate + e2e)
      run: bash scripts/run-final-demo.sh

    - name: Upload demo artifacts
      uses: actions/upload-artifact@v4
      with:
        name: demo-artifacts
        path: |
          output/local_generated.mp4
          output/FINAL_DEMO_SUCCESS.png
          output/FINAL_DEMO_CERT.txt
          test-results/**
