name: Meta Ad Studio CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run asset integrity check
      run: node scripts/ci-check-assets.cjs

    - name: Run linter
      run: npm run lint

    - name: Run unit tests
      run: npm test -- --run

    - name: Run production build (with sourcemaps)
      env:
        NODE_ENV: production
      run: |
        # Ensure Vite emits source maps for release uploads
        npm run build

    - name: Upload source maps to Sentry (optional)
      if: secrets.SENTRY_AUTH_TOKEN != ''
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      run: |
        echo "Sentry upload step placeholder - configure sentry-cli or vite-plugin-sentry in your pipeline"

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright E2E + Visual Tests
      run: npx playwright test --update-snapshots=false
      env:
        CI: true

    - name: Package release zip
      run: |
        zip -r meta-ad-studio-platform-v1.0.zip . -x node_modules/**\* .git/**\* tests/**\*
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: meta-ad-studio-platform-v1.0.zip
        path: meta-ad-studio-platform-v1.0.zip
